name: Validate module

defaults:
  run:
    working-directory: test

steps:
  - uses: actions/checkout@v2
  - uses: hashicorp/setup-terraform@v2

  - name: Terraform fmt
    id: fmt
    run: terraform fmt -check -recursive
    working-directory: .

  - name: Terraform Init
    id: init
    run: terraform init

  - name: Terraform Validate
    id: validate
    run: terraform validate -no-color
